name: Test Project
on: push

jobs:
  test:
    runs-on: macos-latest  # Added the missing 'runs-on' key
    steps:
      - name: Get code
        uses: actions/checkout@v4 # Updated to v4 (latest)

      - name: Run tests
        working-directory: ./WeatherApp
        run: |
          xcodebuild test \
            -project WeatherApp.xcodeproj \
            -scheme WeatherApp \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest'
